# Generated by Django 2.1.7 on 2019-03-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dostopr',
        ),
    ]
