# Generated by Django 2.2.1 on 2020-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_dostopr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dostopr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('rate', models.FloatField()),
                ('photo', models.CharField(max_length=100)),
                ('url', models.CharField(default='null', max_length=200)),
            ],
        ),
    ]
