# Generated by Django 2.2.1 on 2020-05-27 11:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dostopr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Сертификат')),
            ],
        ),
    ]
