# Generated by Django 3.1.4 on 2021-01-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sertificat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dostopr',
        ),
    ]
