# Generated by Django 2.1.7 on 2019-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dostopr',
            name='photo',
            field=models.CharField(max_length=100),
        ),
    ]
